// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @sync/switch-state
const encoding0 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.on ? 1 : 0

    c.uint.encode(state, flags)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      on: (flags & 1) !== 0
    }
  }
}

// @sync/identity
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.publicKey)
    c.string.preencode(state, m.topic)
  },
  encode(state, m) {
    c.string.encode(state, m.publicKey)
    c.string.encode(state, m.topic)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      publicKey: r0,
      topic: r1
    }
  }
}

// @sync/peers
const encoding2 = {
  preencode(state, m) {
    c.uint.preencode(state, m.count)
  },
  encode(state, m) {
    c.uint.encode(state, m.count)
  },
  decode(state) {
    const r0 = c.uint.decode(state)

    return {
      count: r0
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@sync/switch-state':
      return encoding0
    case '@sync/identity':
      return encoding1
    case '@sync/peers':
      return encoding2
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
