// This file is autogenerated by hrpc-c
// !!DO NOT EDIT!!
#ifndef SYNC_HRPC_H
#define SYNC_HRPC_H

#include "sync_schema.h"
#include "hrpc.h"
#include <rpc.h>
#include <stddef.h>
#include <stdint.h>

enum {
  sync_command_set_state = 0,
  sync_command_new_state = 1,
  sync_command_peers_changed = 2,
  sync_command_info = 3,
};

// @sync/set-state (unary)
int
sync_encode_set_state (uint64_t id, const sync_switch_state_t *args, uint8_t **out, size_t *out_len);

int
sync_encode_set_state_error (uint64_t id, hrpc_error_t error, uint8_t **out, size_t *out_len);

// Returns hrpc_ok (fills *result), hrpc_error_response (fills *error), or < 0.
int
sync_decode_set_state_response (const rpc_message_t *msg, sync_switch_state_t *result, hrpc_error_t *error);

// Return hrpc_ok after filling *res, or hrpc_error_response after filling *error.
typedef int (*sync_on_set_state) (void *ctx, const sync_switch_state_t *req, sync_switch_state_t *res, hrpc_error_t *error);

// @sync/new-state (event)
int
sync_encode_new_state (const sync_switch_state_t *args, uint8_t **out, size_t *out_len);

typedef void (*sync_on_new_state) (void *ctx, const sync_switch_state_t *req);

// @sync/peers-changed (event)
int
sync_encode_peers_changed (const sync_peers_t *args, uint8_t **out, size_t *out_len);

typedef void (*sync_on_peers_changed) (void *ctx, const sync_peers_t *req);

// @sync/info (event)
int
sync_encode_info (const sync_identity_t *args, uint8_t **out, size_t *out_len);

typedef void (*sync_on_info) (void *ctx, const sync_identity_t *req);

typedef struct {
  void *ctx;
  sync_on_set_state on_set_state;
  sync_on_new_state on_new_state;
  sync_on_peers_changed on_peers_changed;
  sync_on_info on_info;
} sync_hrpc_handlers_t;

// Dispatch one decoded request. Returns hrpc_dispatch_reply (sets
// *reply_out / *reply_len, caller sends then frees), hrpc_dispatch_no_reply,
// hrpc_dispatch_stream, or < 0 (no reply written).
int
sync_hrpc_dispatch (const sync_hrpc_handlers_t *handlers, const rpc_message_t *msg, uint8_t **reply_out, size_t *reply_len);

#endif // SYNC_HRPC_H
