// This file is autogenerated by hrpc-c
// !!DO NOT EDIT!!
#include "sync_hrpc.h"

#include <compact.h>
#include <stdlib.h>

static int
sync_hrpc__frame (const rpc_message_t *msg, uint8_t **out, size_t *out_len) {
  compact_state_t state = {0, 0, NULL};
  int err = rpc_preencode_message(&state, msg);
  if (err < 0) return hrpc_err_decode;
  state.buffer = malloc(state.end);
  if (state.buffer == NULL) return hrpc_err_alloc;
  err = rpc_encode_message(&state, msg);
  if (err < 0) {
    free(state.buffer);
    return hrpc_err_decode;
  }
  *out = state.buffer;
  *out_len = state.end;
  return 0;
}

int
sync_encode_set_state (uint64_t id, const sync_switch_state_t *args, uint8_t **out, size_t *out_len) {
  compact_state_t payload = {0, 0, NULL};
  int err = sync_switch_state_preencode(&payload, args);
  if (err < 0) return hrpc_err_decode;
  if (payload.end > 0) {
    payload.buffer = malloc(payload.end);
    if (payload.buffer == NULL) return hrpc_err_alloc;
    err = sync_switch_state_encode(&payload, args);
    if (err < 0) {
      free(payload.buffer);
      return hrpc_err_decode;
    }
  }

  rpc_message_t msg = {0};
  msg.type = rpc_request;
  msg.id = id;
  msg.command = sync_command_set_state;
  msg.stream = 0;
  msg.data = payload.buffer;
  msg.len = payload.end;

  err = sync_hrpc__frame(&msg, out, out_len);
  free(payload.buffer);
  return err;
}

int
sync_encode_set_state_error (uint64_t id, hrpc_error_t error, uint8_t **out, size_t *out_len) {
  rpc_message_t msg = {0};
  msg.type = rpc_response;
  msg.id = id;
  msg.error = true;
  msg.stream = 0;
  msg.message = error.message;
  msg.code = error.code;
  msg.status = error.status;
  return sync_hrpc__frame(&msg, out, out_len);
}

int
sync_decode_set_state_response (const rpc_message_t *msg, sync_switch_state_t *result, hrpc_error_t *error) {
  if (msg->error) {
    error->message = msg->message;
    error->code = msg->code;
    error->status = msg->status;
    return hrpc_error_response;
  }
  compact_state_t payload = {0, msg->len, msg->data};
  int err = sync_switch_state_decode(&payload, result);
  if (err < 0) return hrpc_err_decode;
  return hrpc_ok;
}

int
sync_encode_new_state (const sync_switch_state_t *args, uint8_t **out, size_t *out_len) {
  compact_state_t payload = {0, 0, NULL};
  int err = sync_switch_state_preencode(&payload, args);
  if (err < 0) return hrpc_err_decode;
  if (payload.end > 0) {
    payload.buffer = malloc(payload.end);
    if (payload.buffer == NULL) return hrpc_err_alloc;
    err = sync_switch_state_encode(&payload, args);
    if (err < 0) {
      free(payload.buffer);
      return hrpc_err_decode;
    }
  }

  rpc_message_t msg = {0};
  msg.type = rpc_request;
  msg.id = 0;
  msg.command = sync_command_new_state;
  msg.stream = 0;
  msg.data = payload.buffer;
  msg.len = payload.end;

  err = sync_hrpc__frame(&msg, out, out_len);
  free(payload.buffer);
  return err;
}

int
sync_encode_peers_changed (const sync_peers_t *args, uint8_t **out, size_t *out_len) {
  compact_state_t payload = {0, 0, NULL};
  int err = sync_peers_preencode(&payload, args);
  if (err < 0) return hrpc_err_decode;
  if (payload.end > 0) {
    payload.buffer = malloc(payload.end);
    if (payload.buffer == NULL) return hrpc_err_alloc;
    err = sync_peers_encode(&payload, args);
    if (err < 0) {
      free(payload.buffer);
      return hrpc_err_decode;
    }
  }

  rpc_message_t msg = {0};
  msg.type = rpc_request;
  msg.id = 0;
  msg.command = sync_command_peers_changed;
  msg.stream = 0;
  msg.data = payload.buffer;
  msg.len = payload.end;

  err = sync_hrpc__frame(&msg, out, out_len);
  free(payload.buffer);
  return err;
}

int
sync_encode_info (const sync_identity_t *args, uint8_t **out, size_t *out_len) {
  compact_state_t payload = {0, 0, NULL};
  int err = sync_identity_preencode(&payload, args);
  if (err < 0) return hrpc_err_decode;
  if (payload.end > 0) {
    payload.buffer = malloc(payload.end);
    if (payload.buffer == NULL) return hrpc_err_alloc;
    err = sync_identity_encode(&payload, args);
    if (err < 0) {
      free(payload.buffer);
      return hrpc_err_decode;
    }
  }

  rpc_message_t msg = {0};
  msg.type = rpc_request;
  msg.id = 0;
  msg.command = sync_command_info;
  msg.stream = 0;
  msg.data = payload.buffer;
  msg.len = payload.end;

  err = sync_hrpc__frame(&msg, out, out_len);
  free(payload.buffer);
  return err;
}

int
sync_hrpc_dispatch (const sync_hrpc_handlers_t *handlers, const rpc_message_t *msg, uint8_t **reply_out, size_t *reply_len) {
  switch (msg->command) {
  case sync_command_set_state: {
    if (handlers->on_set_state == NULL) return hrpc_err_unknown;
    sync_switch_state_t req = {0};
    compact_state_t in = {0, msg->len, msg->data};
    if (sync_switch_state_decode(&in, &req) < 0) return hrpc_err_decode;
    sync_switch_state_t res = {0};
    hrpc_error_t error = {0};
    int r = handlers->on_set_state(handlers->ctx, &req, &res, &error);
    sync_switch_state_destroy(&req);
    if (r < 0) {
      sync_switch_state_destroy(&res);
      return r;
    }
    if (r == hrpc_error_response) {
      sync_switch_state_destroy(&res);
      rpc_message_t reply = {0};
      reply.type = rpc_response;
      reply.id = msg->id;
      reply.error = true;
      reply.stream = 0;
      reply.message = error.message;
      reply.code = error.code;
      reply.status = error.status;
      r = sync_hrpc__frame(&reply, reply_out, reply_len);
      return r < 0 ? r : hrpc_dispatch_reply;
    }
    compact_state_t payload = {0, 0, NULL};
    if (sync_switch_state_preencode(&payload, &res) < 0) {
      sync_switch_state_destroy(&res);
      return hrpc_err_decode;
    }
    if (payload.end > 0) {
      payload.buffer = malloc(payload.end);
      if (payload.buffer == NULL) {
        sync_switch_state_destroy(&res);
        return hrpc_err_alloc;
      }
      if (sync_switch_state_encode(&payload, &res) < 0) {
        free(payload.buffer);
        sync_switch_state_destroy(&res);
        return hrpc_err_decode;
      }
    }
    sync_switch_state_destroy(&res);
    rpc_message_t reply = {0};
    reply.type = rpc_response;
    reply.id = msg->id;
    reply.error = false;
    reply.stream = 0;
    reply.data = payload.buffer;
    reply.len = payload.end;
    r = sync_hrpc__frame(&reply, reply_out, reply_len);
    free(payload.buffer);
    return r < 0 ? r : hrpc_dispatch_reply;
  }
  case sync_command_new_state: {
    if (handlers->on_new_state == NULL) return hrpc_err_unknown;
    sync_switch_state_t req = {0};
    compact_state_t in = {0, msg->len, msg->data};
    if (sync_switch_state_decode(&in, &req) < 0) return hrpc_err_decode;
    handlers->on_new_state(handlers->ctx, &req);
    sync_switch_state_destroy(&req);
    return hrpc_dispatch_no_reply;
  }
  case sync_command_peers_changed: {
    if (handlers->on_peers_changed == NULL) return hrpc_err_unknown;
    sync_peers_t req = {0};
    compact_state_t in = {0, msg->len, msg->data};
    if (sync_peers_decode(&in, &req) < 0) return hrpc_err_decode;
    handlers->on_peers_changed(handlers->ctx, &req);
    sync_peers_destroy(&req);
    return hrpc_dispatch_no_reply;
  }
  case sync_command_info: {
    if (handlers->on_info == NULL) return hrpc_err_unknown;
    sync_identity_t req = {0};
    compact_state_t in = {0, msg->len, msg->data};
    if (sync_identity_decode(&in, &req) < 0) return hrpc_err_decode;
    handlers->on_info(handlers->ctx, &req);
    sync_identity_destroy(&req);
    return hrpc_dispatch_no_reply;
  }
  default:
    return hrpc_err_unknown;
  }
}
