// This file is autogenerated by hyperschema-c
// !!DO NOT EDIT!!

#include "sync_schema.h"

int
sync_switch_state_preencode (compact_state_t *state, const sync_switch_state_t *value)
{
  int err;
  uint64_t flags = 0;
  if (value->on) flags |= ((uint64_t)1 << 0);
  if ((err = compact_preencode_uint(state, flags)) < 0) return err;
  return 0;
}

int
sync_switch_state_encode (compact_state_t *state, const sync_switch_state_t *value)
{
  int err;
  uint64_t flags = 0;
  if (value->on) flags |= ((uint64_t)1 << 0);
  if ((err = compact_encode_uint(state, flags)) < 0) return err;
  return 0;
}

int
sync_switch_state_decode (compact_state_t *state, sync_switch_state_t *result)
{
  int err;
  uint64_t flags = 0;
  if ((err = compact_decode_uint(state, &flags)) < 0) return err;
  result->on = (flags & ((uint64_t)1 << 0)) != 0;
  return 0;
}

void
sync_switch_state_destroy (sync_switch_state_t *result)
{
}

int
sync_identity_preencode (compact_state_t *state, const sync_identity_t *value)
{
  int err;
  if ((err = compact_preencode_utf8(state, value->public_key)) < 0) return err;
  if ((err = compact_preencode_utf8(state, value->topic)) < 0) return err;
  return 0;
}

int
sync_identity_encode (compact_state_t *state, const sync_identity_t *value)
{
  int err;
  if ((err = compact_encode_utf8(state, value->public_key)) < 0) return err;
  if ((err = compact_encode_utf8(state, value->topic)) < 0) return err;
  return 0;
}

int
sync_identity_decode (compact_state_t *state, sync_identity_t *result)
{
  int err;
  if ((err = compact_decode_utf8(state, &result->public_key)) < 0) return err;
  if ((err = compact_decode_utf8(state, &result->topic)) < 0) return err;
  return 0;
}

void
sync_identity_destroy (sync_identity_t *result)
{
}

int
sync_peers_preencode (compact_state_t *state, const sync_peers_t *value)
{
  int err;
  if ((err = compact_preencode_uint(state, value->count)) < 0) return err;
  return 0;
}

int
sync_peers_encode (compact_state_t *state, const sync_peers_t *value)
{
  int err;
  if ((err = compact_encode_uint(state, value->count)) < 0) return err;
  return 0;
}

int
sync_peers_decode (compact_state_t *state, sync_peers_t *result)
{
  int err;
  if ((err = compact_decode_uint(state, &result->count)) < 0) return err;
  return 0;
}

void
sync_peers_destroy (sync_peers_t *result)
{
}
