// This file is autogenerated by hyperschema-c
// !!DO NOT EDIT!!
// Schema Version: 1

#ifndef SYNC_SCHEMA_H
#define SYNC_SCHEMA_H

#include <compact.h>
#include <stdbool.h>

// @sync/switch-state
typedef struct sync_switch_state_s {
  bool on;
} sync_switch_state_t;

int
sync_switch_state_preencode (compact_state_t *state, const sync_switch_state_t *value);

int
sync_switch_state_encode (compact_state_t *state, const sync_switch_state_t *value);

int
sync_switch_state_decode (compact_state_t *state, sync_switch_state_t *result);

void
sync_switch_state_destroy (sync_switch_state_t *result);

// @sync/identity
typedef struct sync_identity_s {
  utf8_string_view_t public_key; /* borrows from decode buffer */
  utf8_string_view_t topic; /* borrows from decode buffer */
} sync_identity_t;

int
sync_identity_preencode (compact_state_t *state, const sync_identity_t *value);

int
sync_identity_encode (compact_state_t *state, const sync_identity_t *value);

int
sync_identity_decode (compact_state_t *state, sync_identity_t *result);

void
sync_identity_destroy (sync_identity_t *result);

// @sync/peers
typedef struct sync_peers_s {
  uint64_t count;
} sync_peers_t;

int
sync_peers_preencode (compact_state_t *state, const sync_peers_t *value);

int
sync_peers_encode (compact_state_t *state, const sync_peers_t *value);

int
sync_peers_decode (compact_state_t *state, sync_peers_t *result);

void
sync_peers_destroy (sync_peers_t *result);

#endif // SYNC_SCHEMA_H
