// This file is autogenerated by the hyperschema compiler
// !!DO NOT EDIT THIS FILE!!
// Schema Version: 1

import CompactEncoding
import Foundation

public func encode<C: Codec>(_ codec: C, _ value: C.Value) throws -> Data {
  var state = State()
  codec.preencode(&state, value)
  state.allocate()
  try codec.encode(&state, value)
  return state.buffer
}

public func decode<C: Codec>(_ codec: C, _ data: Data) throws -> C.Value {
  var state = State(data)
  return try codec.decode(&state)
}

// @sync/switch-state
public struct SwitchState {
  public var on: Bool

  public init(on: Bool = false) {
    self.on = on
  }
}

public struct SwitchStateCodec: Codec {
  public typealias Value = SwitchState

  let _uint = Primitive.UInt()

  public init() {}

  public func preencode(_ state: inout State, _ value: SwitchState) {
    var _flags: UInt = 0
    if value.on { _flags |= 1 }
    _uint.preencode(&state, _flags)
  }

  public func encode(_ state: inout State, _ value: SwitchState) throws {
    var _flags: UInt = 0
    if value.on { _flags |= 1 }
    try _uint.encode(&state, _flags)
  }

  public func decode(_ state: inout State) throws -> SwitchState {
    let _flags = try _uint.decode(&state)
    let on = _flags & 1 != 0
    return SwitchState(
      on: on
    )
  }
}

public let switchState = SwitchStateCodec()

// @sync/identity
public struct Identity {
  public var publicKey: String
  public var topic: String

  public init(publicKey: String, topic: String) {
    self.publicKey = publicKey
    self.topic = topic
  }
}

public struct IdentityCodec: Codec {
  public typealias Value = Identity

  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: Identity) {
    _string.preencode(&state, value.publicKey)
    _string.preencode(&state, value.topic)
  }

  public func encode(_ state: inout State, _ value: Identity) throws {
    try _string.encode(&state, value.publicKey)
    try _string.encode(&state, value.topic)
  }

  public func decode(_ state: inout State) throws -> Identity {
    let publicKey = try _string.decode(&state)
    let topic = try _string.decode(&state)
    return Identity(
      publicKey: publicKey,
      topic: topic
    )
  }
}

public let identity = IdentityCodec()

// @sync/peers
public struct Peers {
  public var count: UInt

  public init(count: UInt) {
    self.count = count
  }
}

public struct PeersCodec: Codec {
  public typealias Value = Peers

  let _uint = Primitive.UInt()

  public init() {}

  public func preencode(_ state: inout State, _ value: Peers) {
    _uint.preencode(&state, value.count)
  }

  public func encode(_ state: inout State, _ value: Peers) throws {
    try _uint.encode(&state, value.count)
  }

  public func decode(_ state: inout State) throws -> Peers {
    let count = try _uint.decode(&state)
    return Peers(
      count: count
    )
  }
}

public let peers = PeersCodec()
