// This file is autogenerated by the hrpc compiler

import BareRPC
import CompactEncoding
import Foundation
import Schema

public class HRPC {
  private let _rpc: RPC
  private let _forwarder: _HRPCDelegateForwarder
  private var _handlers: [String: Any] = [:]

  public init<D: RPCDelegate>(delegate: D) {
    let forwarder = _HRPCDelegateForwarder(transport: delegate)
    self._rpc = RPC(delegate: forwarder)
    self._forwarder = forwarder
    forwarder.hrpc = self
  }

  public func receive(_ data: Data) async {
    await self._rpc.receive(data)
  }

  // Request/response — client
  public func setState(_ args: SwitchState? = nil) async throws -> SwitchState {
    let encoded = try args.map { try _encode(switchState, $0) }
    guard let raw = try await _rpc.request(0, data: encoded) else {
      throw RPCRemoteError(message: "Missing response", code: "MISSING_RESPONSE")
    }
    return try _decode(switchState, raw)
  }

  public func onSetState(_ handler: @escaping (SwitchState?) async throws -> SwitchState) {
    _handlers["@sync/set-state"] = handler
  }

  // Send-only — client (fire and forget)
  public func newState(_ args: SwitchState? = nil) async throws {
    let encoded = try args.map { try _encode(switchState, $0) }
    await _rpc.event(1, data: encoded)
  }

  public func onNewState(_ handler: @escaping (SwitchState?) async -> Void) {
    _handlers["@sync/new-state"] = handler
  }

  // Send-only — client (fire and forget)
  public func peersChanged(_ args: Peers? = nil) async throws {
    let encoded = try args.map { try _encode(peers, $0) }
    await _rpc.event(2, data: encoded)
  }

  public func onPeersChanged(_ handler: @escaping (Peers?) async -> Void) {
    _handlers["@sync/peers-changed"] = handler
  }

  // Send-only — client (fire and forget)
  public func info(_ args: Identity? = nil) async throws {
    let encoded = try args.map { try _encode(identity, $0) }
    await _rpc.event(3, data: encoded)
  }

  public func onInfo(_ handler: @escaping (Identity?) async -> Void) {
    _handlers["@sync/info"] = handler
  }

  fileprivate func _dispatchRequest(_ req: IncomingRequest) async {
    await _dispatchNormal(req)
  }
  private func _dispatchNormal(_ req: IncomingRequest) async {
    switch req.command {
    case 0:   // @sync/set-state
      guard let handler = _handlers["@sync/set-state"] as? (SwitchState?) async throws -> SwitchState else { await req.reject("No handler registered", code: "NO_HANDLER"); return }
      do {
        let args: SwitchState? = try req.data.map { try _decode(switchState, $0) }
        let response = try await handler(args)
        await req.reply(try _encode(switchState, response))
      } catch {
        await req.reject(error.localizedDescription, code: "HANDLER_ERROR")
      }
    default:
      await req.reject("Unknown command", code: "UNKNOWN_COMMAND")
    }
  }
  fileprivate func _dispatchEvent(_ event: IncomingEvent) async {
    switch event.command {
    case 1:   // @sync/new-state
      guard let handler = _handlers["@sync/new-state"] as? (SwitchState?) async -> Void else { return }
      do {
        let args: SwitchState? = try event.data.map { try _decode(switchState, $0) }
        await handler(args)
      } catch {
        _forwarder.transport.rpc(_rpc, didFailWith: error)
      }
    case 2:   // @sync/peers-changed
      guard let handler = _handlers["@sync/peers-changed"] as? (Peers?) async -> Void else { return }
      do {
        let args: Peers? = try event.data.map { try _decode(peers, $0) }
        await handler(args)
      } catch {
        _forwarder.transport.rpc(_rpc, didFailWith: error)
      }
    case 3:   // @sync/info
      guard let handler = _handlers["@sync/info"] as? (Identity?) async -> Void else { return }
      do {
        let args: Identity? = try event.data.map { try _decode(identity, $0) }
        await handler(args)
      } catch {
        _forwarder.transport.rpc(_rpc, didFailWith: error)
      }
    default:
      break
    }
  }

  private func _encode<C: Codec>(_ codec: C, _ value: C.Value) throws -> Data {
    var state = State()
    codec.preencode(&state, value)
    state.allocate()
    try codec.encode(&state, value)
    return state.buffer
  }

  private func _decode<C: Codec>(_ codec: C, _ data: Data) throws -> C.Value {
    var state = State(data)
    return try codec.decode(&state)
  }
}

private final class _HRPCDelegateForwarder: RPCDelegate {
  let transport: any RPCDelegate
  weak var hrpc: HRPC?

  init<D: RPCDelegate>(transport: D) {
    self.transport = transport
  }

  func rpc(_ rpc: RPC, send data: Data) {
    transport.rpc(rpc, send: data)
  }

  func rpc(_ rpc: RPC, didFailWith error: Error) {
    transport.rpc(rpc, didFailWith: error)
  }

  func rpc(_ rpc: RPC, didReceiveRequest req: IncomingRequest) async throws {
    await hrpc?._dispatchRequest(req)
  }

  func rpc(_ rpc: RPC, didReceiveEvent event: IncomingEvent) async {
    await hrpc?._dispatchEvent(event)
  }
}
