name: Integrate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  integrate:
    runs-on: ubuntu-latest
    name: Integrate
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - run: npm run lint
      - run: npm test
